# Generated by Django 4.2.5 on 2023-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='imageurl',
            field=models.CharField(blank=True, default=False, max_length=2083),
        ),
    ]
